# Generated by Django 4.2.7 on 2026-02-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Clinic or practice name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, help_text='Veterinary license number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Shelter registration number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shelter_description',
            field=models.TextField(blank=True, help_text='Shelter description', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shelter_name',
            field=models.CharField(blank=True, help_text='Shelter display name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text='Specialization area', max_length=255, null=True),
        ),
    ]
