# Generated by Django 4.2.7 on 2026-02-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certification_document',
            field=models.FileField(blank=True, help_text='Veterinarian certification document', null=True, upload_to='verification/vet/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_document',
            field=models.FileField(blank=True, help_text='Veterinarian license document', null=True, upload_to='verification/vet/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_document',
            field=models.FileField(blank=True, help_text='Shelter organization verification document', null=True, upload_to='verification/shelter/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_certificate',
            field=models.FileField(blank=True, help_text='Shelter registration certificate', null=True, upload_to='verification/shelter/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], db_index=True, default='pending', help_text='Verification status for Vet/Shelter roles', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VerificationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('submission_received', 'Submission Received'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_ve_user_id_3f5078_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='Admin who performed the action (null for submit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User whose verification was acted upon', on_delete=django.db.models.deletion.CASCADE, related_name='verification_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_ve_user_id_118075_idx'), models.Index(fields=['action'], name='accounts_ve_action_2b2fca_idx')],
            },
        ),
    ]
