# Generated by Django 4.2.7 on 2025-12-22 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pet name', max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('other', 'Other')], help_text='Type of pet', max_length=20)),
                ('breed', models.CharField(help_text='Pet breed', max_length=100)),
                ('age', models.IntegerField(help_text='Age in months')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('health_status', models.TextField(help_text='Current health status and medical information')),
                ('description', models.TextField(help_text='Detailed description of the pet')),
                ('location', models.CharField(help_text='Location/address where pet is available', max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Adoption'), ('adopted', 'Adopted')], default='available', help_text='Adoption status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(help_text='Shelter that owns this pet', limit_choices_to={'role': 'shelter'}, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Pet image file', upload_to='pet_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(help_text='Pet this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Pet Image',
                'verbose_name_plural': 'Pet Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['pet_type', 'status'], name='pets_pet_pet_typ_a44fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['shelter', 'status'], name='pets_pet_shelter_1ad1de_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['breed'], name='pets_pet_breed_71a09c_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['location'], name='pets_pet_locatio_44d479_idx'),
        ),
    ]
