# Generated by Django 4.2.7 on 2026-01-23 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(help_text='Pet being saved', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='pets.pet')),
                ('user', models.ForeignKey(help_text='User who saved the pet', limit_choices_to={'role': 'adopter'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Pet',
                'verbose_name_plural': 'Saved Pets',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user'], name='pets_savedp_user_id_0ad8f8_idx')],
                'unique_together': {('user', 'pet')},
            },
        ),
        migrations.CreateModel(
            name='RewardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Number of points earned')),
                ('source', models.CharField(choices=[('adoption', 'Pet Adoption'), ('review', 'Shelter Review'), ('referral', 'User Referral'), ('engagement', 'Platform Engagement'), ('bonus', 'Bonus Points')], help_text='Source of the points', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Description of how points were earned', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_pet', models.ForeignKey(blank=True, help_text='Pet related to these points (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_points', to='pets.pet')),
                ('user', models.ForeignKey(help_text='User earning the points', on_delete=django.db.models.deletion.CASCADE, related_name='reward_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Point',
                'verbose_name_plural': 'Reward Points',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pets_reward_user_id_628a31_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Message subject', max_length=200)),
                ('body', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether message has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User receiving the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('related_pet', models.ForeignKey(blank=True, help_text='Pet related to this message (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='pets.pet')),
                ('sender', models.ForeignKey(help_text='User sending the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='pets_messag_recipie_e06fa9_idx'), models.Index(fields=['sender'], name='pets_messag_sender__0aa3df_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Request status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from adopter', null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('adopter', models.ForeignKey(help_text='User requesting to adopt', limit_choices_to={'role': 'adopter'}, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(help_text='Pet being requested for adoption', on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Shelter user who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_adoption_requests', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(help_text='Shelter that owns the pet', limit_choices_to={'role': 'shelter'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_adoption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adoption Request',
                'verbose_name_plural': 'Adoption Requests',
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['adopter', 'status'], name='pets_adopti_adopter_2fd0b7_idx'), models.Index(fields=['shelter', 'status'], name='pets_adopti_shelter_5b7451_idx'), models.Index(fields=['pet', 'status'], name='pets_adopti_pet_id_909171_idx')],
                'unique_together': {('pet', 'adopter')},
            },
        ),
    ]
