# Generated by Django 4.2.7 on 2026-02-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_chat_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional document attachment', null=True, upload_to='message_docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, help_text='Message content (optional if attachment)'),
        ),
    ]
