# Generated by Django 4.2.7 on 2026-02-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_add_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopted_date',
            field=models.DateTimeField(blank=True, help_text='Date when adoption was confirmed (set when approved)', null=True),
        ),
    ]
