# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_add_adopted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('updated', 'Updated'),
                    ('approved', 'Approved'),
                    ('adopted', 'Adopted'),
                    ('rejected', 'Rejected'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending',
                help_text='Request status',
                max_length=20,
            ),
        ),
    ]
