# Generated by Django 4.2.7 on 2025-12-22 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('checkup', 'Check-up'), ('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('surgery', 'Surgery'), ('emergency', 'Emergency'), ('other', 'Other')], help_text='Type of medical record', max_length=20)),
                ('title', models.CharField(help_text='Title/Summary of the record', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the medical record')),
                ('date', models.DateField(help_text='Date of the medical procedure/visit')),
                ('next_due_date', models.DateField(blank=True, help_text='Next due date for follow-up (for vaccinations/check-ups)', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the procedure (optional)', max_digits=10, null=True)),
                ('documents', models.FileField(blank=True, help_text='Medical documents (reports, certificates, etc.)', null=True, upload_to='medical_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(help_text='Pet this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet')),
                ('veterinarian', models.ForeignKey(help_text='Veterinarian who created this record', limit_choices_to={'role': 'veterinarian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('rabies', 'Rabies'), ('dhpp', 'DHPP (Distemper, Hepatitis, Parvovirus, Parainfluenza)'), ('bordetella', 'Bordetella'), ('feline_leukemia', 'Feline Leukemia'), ('feline_distemper', 'Feline Distemper (FVRCP)'), ('other', 'Other')], help_text='Type of vaccine administered', max_length=50)),
                ('vaccine_name', models.CharField(help_text='Name/brand of the vaccine', max_length=200)),
                ('batch_number', models.CharField(blank=True, help_text='Vaccine batch number', max_length=100, null=True)),
                ('administered_date', models.DateField(help_text='Date vaccine was administered')),
                ('next_due_date', models.DateField(help_text='Next vaccination due date')),
                ('is_booster', models.BooleanField(default=False, help_text='Is this a booster shot?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the vaccination', null=True)),
                ('medical_record', models.OneToOneField(help_text='Medical record associated with this vaccination', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='veterinary.medicalrecord')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('medication', 'Medication'), ('therapy', 'Therapy'), ('dental', 'Dental Care'), ('grooming', 'Grooming'), ('parasite_control', 'Parasite Control'), ('other', 'Other')], help_text='Type of treatment', max_length=30)),
                ('treatment_name', models.CharField(help_text='Name of the treatment/medication', max_length=200)),
                ('dosage', models.CharField(blank=True, help_text='Dosage information', max_length=200, null=True)),
                ('frequency', models.CharField(blank=True, help_text='Frequency of administration (e.g., "Twice daily", "Once a week")', max_length=100, null=True)),
                ('start_date', models.DateField(help_text='Treatment start date')),
                ('end_date', models.DateField(blank=True, help_text='Treatment end date (if applicable)', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for the treatment', null=True)),
                ('medical_record', models.ForeignKey(help_text='Medical record associated with this treatment', on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='veterinary.medicalrecord')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('vaccination', 'Vaccination Due'), ('checkup', 'Check-up Due'), ('treatment', 'Treatment Due'), ('medication', 'Medication Reminder'), ('other', 'Other')], help_text='Type of reminder', max_length=20)),
                ('title', models.CharField(help_text='Reminder title', max_length=200)),
                ('description', models.TextField(help_text='Reminder description')),
                ('due_date', models.DateField(help_text='Date when the reminder is due')),
                ('reminder_date', models.DateField(help_text='Date to send the reminder (usually a few days before due_date)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Reminder status', max_length=20)),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring reminder?')),
                ('recurrence_interval', models.IntegerField(blank=True, help_text='Recurrence interval in days (e.g., 365 for annual)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the reminder was sent', null=True)),
                ('medical_record', models.ForeignKey(blank=True, help_text='Related medical record (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='veterinary.medicalrecord')),
                ('pet', models.ForeignKey(help_text='Pet this reminder is for', on_delete=django.db.models.deletion.CASCADE, related_name='health_reminders', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Health Reminder',
                'verbose_name_plural': 'Health Reminders',
                'ordering': ['due_date', 'reminder_date'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['pet', 'record_type'], name='veterinary__pet_id_ade1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['veterinarian', 'date'], name='veterinary__veterin_b5a3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['next_due_date'], name='veterinary__next_du_7ebdee_idx'),
        ),
        migrations.AddIndex(
            model_name='healthreminder',
            index=models.Index(fields=['pet', 'status'], name='veterinary__pet_id_08bb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthreminder',
            index=models.Index(fields=['reminder_date', 'status'], name='veterinary__reminde_7b0dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='healthreminder',
            index=models.Index(fields=['due_date'], name='veterinary__due_dat_c501e0_idx'),
        ),
    ]
