# Generated by Django 4.2.7 on 2025-12-22 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('vaccination', 'Vaccination Reminder'), ('checkup', 'Check-up Reminder'), ('treatment', 'Treatment Reminder'), ('medication', 'Medication Reminder'), ('overdue', 'Overdue Reminder'), ('other', 'Other')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Has the notification been read?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('health_reminder', models.ForeignKey(blank=True, help_text='Related health reminder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='veterinary.healthreminder')),
                ('pet', models.ForeignKey(help_text='Pet this notification is about', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pets.pet')),
                ('user', models.ForeignKey(help_text='Adopter to receive the notification', limit_choices_to={'role': 'adopter'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='veterinary__user_id_8f3ff0_idx'), models.Index(fields=['pet', 'notification_type'], name='veterinary__pet_id_0b1f3c_idx')],
            },
        ),
    ]
