# Generated by Django 4.2.7 on 2025-12-22 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('other', 'Other')], help_text='Type of pet found', max_length=20)),
                ('breed', models.CharField(blank=True, help_text='Breed of the pet (if identifiable)', max_length=100, null=True)),
                ('color', models.CharField(help_text='Color/markings of the pet', max_length=100)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size of the pet', max_length=20, null=True)),
                ('age_estimate', models.CharField(blank=True, help_text='Estimated age (e.g., "young", "adult", "senior")', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], help_text='Gender of the pet', max_length=10, null=True)),
                ('description', models.TextField(help_text='Detailed description of the found pet')),
                ('found_location', models.CharField(help_text='Location where pet was found', max_length=200)),
                ('found_date', models.DateField(help_text='Date when pet was found')),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('current_location', models.CharField(blank=True, help_text='Current location of the pet (if different from found location)', max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', help_text='Status of the report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the report was resolved', null=True)),
                ('user', models.ForeignKey(help_text='User who reported the found pet', on_delete=django.db.models.deletion.CASCADE, related_name='found_pet_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Found Pet Report',
                'verbose_name_plural': 'Found Pet Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostPetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(help_text='Name of the lost pet', max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('other', 'Other')], help_text='Type of pet', max_length=20)),
                ('breed', models.CharField(blank=True, help_text='Breed of the pet', max_length=100, null=True)),
                ('color', models.CharField(help_text='Color/markings of the pet', max_length=100)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size of the pet', max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, help_text='Age in months', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], help_text='Gender of the pet', max_length=10, null=True)),
                ('description', models.TextField(help_text='Detailed description of the pet')),
                ('last_seen_location', models.CharField(help_text='Location where pet was last seen', max_length=200)),
                ('last_seen_date', models.DateField(help_text='Date when pet was last seen')),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('reward_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount offered (optional)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', help_text='Status of the report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the report was resolved', null=True)),
                ('user', models.ForeignKey(help_text='User who reported the lost pet', on_delete=django.db.models.deletion.CASCADE, related_name='lost_pet_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost Pet Report',
                'verbose_name_plural': 'Lost Pet Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Similarity score (0-100)')),
                ('match_reasons', models.TextField(help_text='Reasons why this is a potential match')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', help_text='Status of the match', max_length=20)),
                ('confirmed_by_lost_owner', models.BooleanField(default=False, help_text='Has the lost pet owner confirmed this match?')),
                ('confirmed_by_finder', models.BooleanField(default=False, help_text='Has the finder confirmed this match?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the match was resolved', null=True)),
                ('found_report', models.ForeignKey(help_text='Found pet report', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='lost_found.foundpetreport')),
                ('lost_report', models.ForeignKey(help_text='Lost pet report', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='lost_found.lostpetreport')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Pet image', upload_to='lost_found_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_report', models.ForeignKey(blank=True, help_text='Found pet report this image belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lost_found.foundpetreport')),
                ('lost_report', models.ForeignKey(blank=True, help_text='Lost pet report this image belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lost_found.lostpetreport')),
            ],
            options={
                'verbose_name': 'Pet Image',
                'verbose_name_plural': 'Pet Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('match_found', 'Match Found'), ('match_confirmed', 'Match Confirmed'), ('match_rejected', 'Match Rejected')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Has the notification been read?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('match', models.ForeignKey(help_text='Match this notification is about', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lost_found.match')),
                ('user', models.ForeignKey(help_text='User to receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='match_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Notification',
                'verbose_name_plural': 'Match Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='lost_found__user_id_db4d3c_idx'), models.Index(fields=['match', 'notification_type'], name='lost_found__match_i_437db3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['lost_report', 'status'], name='lost_found__lost_re_5754aa_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['found_report', 'status'], name='lost_found__found_r_fd7dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'match_score'], name='lost_found__status_bbef4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('lost_report', 'found_report')},
        ),
        migrations.AddIndex(
            model_name='lostpetreport',
            index=models.Index(fields=['pet_type', 'status'], name='lost_found__pet_typ_45bf2f_idx'),
        ),
        migrations.AddIndex(
            model_name='lostpetreport',
            index=models.Index(fields=['last_seen_location'], name='lost_found__last_se_e213a8_idx'),
        ),
        migrations.AddIndex(
            model_name='lostpetreport',
            index=models.Index(fields=['status', 'created_at'], name='lost_found__status_b62535_idx'),
        ),
        migrations.AddIndex(
            model_name='foundpetreport',
            index=models.Index(fields=['pet_type', 'status'], name='lost_found__pet_typ_63e8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='foundpetreport',
            index=models.Index(fields=['found_location'], name='lost_found__found_l_728767_idx'),
        ),
        migrations.AddIndex(
            model_name='foundpetreport',
            index=models.Index(fields=['status', 'created_at'], name='lost_found__status_963308_idx'),
        ),
    ]
